//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.MachinesReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MachinesReference.IMachinesService")]
    public interface IMachinesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/Create", ReplyAction="http://tempuri.org/IMachinesService/CreateResponse")]
        bool Create(Model.Machine machine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/Create", ReplyAction="http://tempuri.org/IMachinesService/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(Model.Machine machine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/Edit", ReplyAction="http://tempuri.org/IMachinesService/EditResponse")]
        bool Edit(Model.Machine machine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/Edit", ReplyAction="http://tempuri.org/IMachinesService/EditResponse")]
        System.Threading.Tasks.Task<bool> EditAsync(Model.Machine machine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/Delete", ReplyAction="http://tempuri.org/IMachinesService/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/Delete", ReplyAction="http://tempuri.org/IMachinesService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/Get", ReplyAction="http://tempuri.org/IMachinesService/GetResponse")]
        Model.Machine Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/Get", ReplyAction="http://tempuri.org/IMachinesService/GetResponse")]
        System.Threading.Tasks.Task<Model.Machine> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/GetAll", ReplyAction="http://tempuri.org/IMachinesService/GetAllResponse")]
        Model.Machine[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachinesService/GetAll", ReplyAction="http://tempuri.org/IMachinesService/GetAllResponse")]
        System.Threading.Tasks.Task<Model.Machine[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMachinesServiceChannel : WebApplication.MachinesReference.IMachinesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MachinesServiceClient : System.ServiceModel.ClientBase<WebApplication.MachinesReference.IMachinesService>, WebApplication.MachinesReference.IMachinesService {
        
        public MachinesServiceClient() {
        }
        
        public MachinesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MachinesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachinesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachinesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create(Model.Machine machine) {
            return base.Channel.Create(machine);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(Model.Machine machine) {
            return base.Channel.CreateAsync(machine);
        }
        
        public bool Edit(Model.Machine machine) {
            return base.Channel.Edit(machine);
        }
        
        public System.Threading.Tasks.Task<bool> EditAsync(Model.Machine machine) {
            return base.Channel.EditAsync(machine);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public Model.Machine Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Model.Machine> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public Model.Machine[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Model.Machine[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
