//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.EmployeeLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeLogin.IEmployeeLogin")]
    public interface IEmployeeLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeLogin/CheckData", ReplyAction="http://tempuri.org/IEmployeeLogin/CheckDataResponse")]
        bool CheckData(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeLogin/CheckData", ReplyAction="http://tempuri.org/IEmployeeLogin/CheckDataResponse")]
        System.Threading.Tasks.Task<bool> CheckDataAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeLoginChannel : DesktopApp.EmployeeLogin.IEmployeeLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeLoginClient : System.ServiceModel.ClientBase<DesktopApp.EmployeeLogin.IEmployeeLogin>, DesktopApp.EmployeeLogin.IEmployeeLogin {
        
        public EmployeeLoginClient() {
        }
        
        public EmployeeLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckData(string login, string password) {
            return base.Channel.CheckData(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckDataAsync(string login, string password) {
            return base.Channel.CheckDataAsync(login, password);
        }
    }
}
